# Generated by Django 2.2.6 on 2019-11-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_is_shared'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',)},
        ),
    ]
